import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import React from 'react';
import { Document, Page, Text, View, Image, StyleSheet, renderToBuffer } from '@react-pdf/renderer';

const GREEN = '#1a6b3c';
const LIGHT_GREEN = '#e6f4ea';
const TEXT_DARK = '#1f2937';
const TEXT_MUTED = '#4b5563';
const BORDER = '#e5e7eb';
const LIGHT_BG = '#f9fafb';

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

const s = StyleSheet.create({
  page: { padding: 45, fontFamily: 'Helvetica', fontSize: 9, color: TEXT_DARK, lineHeight: 1.5 },
  topBar: { height: 6, backgroundColor: GREEN, position: 'absolute', top: 0, left: 0, right: 0 },
  footer: { position: 'absolute', bottom: 25, left: 45, right: 45, flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 0.5, borderTopColor: BORDER, paddingTop: 8 },
  footerText: { fontSize: 7, color: TEXT_MUTED },
  
  // Cover Page styles
  coverContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  coverTitle: { fontSize: 24, fontFamily: 'Helvetica-Bold', color: GREEN, marginBottom: 8, textAlign: 'center' },
  coverSubtitle: { fontSize: 14, color: TEXT_MUTED, marginBottom: 20 },
  coverDate: { fontSize: 10, color: TEXT_DARK, marginBottom: 30 },
  coverPowered: { fontSize: 8, color: TEXT_MUTED, textTransform: 'uppercase', letterSpacing: 1 },
  logo: { maxHeight: 80, maxWidth: 160, marginBottom: 20, objectFit: 'contain' },

  // Sections
  sectionHeader: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: GREEN, borderBottomWidth: 1, borderBottomColor: GREEN, paddingBottom: 4, marginBottom: 12, textTransform: 'uppercase' },
  grid: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  card: { flex: 1, backgroundColor: LIGHT_BG, borderLeftWidth: 3, borderLeftColor: GREEN, padding: 10, borderRadius: 4 },
  cardLabel: { fontSize: 7, color: TEXT_MUTED, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', marginBottom: 3 },
  cardValue: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: TEXT_DARK },

  // Progress Bar
  progressTrack: { height: 8, backgroundColor: BORDER, borderRadius: 4, width: '100%', marginTop: 8, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: GREEN },

  // Tables
  tableHeader: { flexDirection: 'row', backgroundColor: GREEN, paddingVertical: 6, paddingHorizontal: 4, borderRadius: 2 },
  th: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: 'white', textTransform: 'uppercase' },
  tableRow: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 4, borderBottomWidth: 0.5, borderBottomColor: BORDER },
  tableRowAlt: { backgroundColor: LIGHT_BG },
  td: { fontSize: 8, color: TEXT_DARK },
  tdBold: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: TEXT_DARK },
});

interface PDFReportProps {
  shop: any;
  month: number;
  year: number;
  data: any;
}

const ReportPDFDocument = ({ shop, month, year, data }: PDFReportProps) => {
  const periodStr = `${MONTHS[month - 1]} ${year}`;
  const generatedOn = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });

  return (
    <Document>
      {/* PAGE 1: COVER */}
      <Page size="A4" style={s.page}>
        <View style={s.topBar} />
        <View style={s.coverContainer}>
          {shop.logo_url && (
            <Image src={shop.logo_url} style={s.logo} />
          )}
          <Text style={s.coverTitle}>{shop.name}</Text>
          <Text style={s.coverSubtitle}>Monthly Business Report</Text>
          <Text style={s.coverDate}>For the period: {periodStr}</Text>
          <Text style={{ fontSize: 9, color: TEXT_MUTED, marginBottom: 8 }}>Generated on: {generatedOn}</Text>
          <Text style={s.coverPowered}>Powered by TruBill Invoice</Text>
        </View>
        <View style={s.footer}>
          <Text style={s.footerText}>{shop.name}</Text>
          <Text style={s.footerText}>Page 1</Text>
          <Text style={s.footerText}>Generated by TruBill Invoice</Text>
        </View>
      </Page>

      {/* PAGE 2: SALES SUMMARY */}
      <Page size="A4" style={s.page}>
        <View style={s.topBar} />
        <Text style={s.sectionHeader}>Page 2 — Sales Summary</Text>
        
        <View style={s.grid}>
          <View style={s.card}>
            <Text style={s.cardLabel}>Invoices Sent</Text>
            <Text style={s.cardValue}>{data.salesSummary.totalInvoicesSent}</Text>
          </View>
          <View style={s.card}>
            <Text style={s.cardLabel}>Total Billed</Text>
            <Text style={s.cardValue}>₹{data.salesSummary.totalBilled.toLocaleString('en-IN')}</Text>
          </View>
          <View style={s.card}>
            <Text style={s.cardLabel}>Total Collected</Text>
            <Text style={s.cardValue}>₹{data.salesSummary.totalCollected.toLocaleString('en-IN')}</Text>
          </View>
        </View>

        <View style={s.grid}>
          <View style={[s.card, { borderLeftColor: '#e53e3e' }]}>
            <Text style={s.cardLabel}>Outstanding Balance</Text>
            <Text style={[s.cardValue, { color: '#e53e3e' }]}>₹{data.salesSummary.outstanding.toLocaleString('en-IN')}</Text>
          </View>
          <View style={[s.card, { borderLeftColor: '#1a6b3c' }]}>
            <Text style={s.cardLabel}>Collection Rate</Text>
            <Text style={[s.cardValue, { color: '#1a6b3c' }]}>{data.salesSummary.collectionRate}%</Text>
          </View>
        </View>

        <View style={{ marginTop: 15, backgroundColor: LIGHT_BG, padding: 15, borderRadius: 6 }}>
          <Text style={{ fontSize: 9, fontFamily: 'Helvetica-Bold', color: TEXT_DARK }}>Collection Efficiency</Text>
          <View style={s.progressTrack}>
            <View style={[s.progressFill, { width: `${Math.min(100, data.salesSummary.collectionRate)}%` }]} />
          </View>
          <Text style={{ fontSize: 8, color: TEXT_MUTED, marginTop: 4 }}>
            {data.salesSummary.collectionRate}% of billed revenue collected this month.
          </Text>
        </View>

        <View style={s.footer}>
          <Text style={s.footerText}>{shop.name} | {periodStr}</Text>
          <Text style={s.footerText}>Page 2</Text>
          <Text style={s.footerText}>Generated by TruBill Invoice</Text>
        </View>
      </Page>

      {/* PAGE 3: GST SUMMARY (if registered) */}
      {shop.gst_registered && data.gstSummary && (
        <Page size="A4" style={s.page}>
          <View style={s.topBar} />
          <Text style={s.sectionHeader}>Page 3 — GST Summary</Text>
          
          <View style={s.grid}>
            <View style={s.card}>
              <Text style={s.cardLabel}>Taxable Sales</Text>
              <Text style={s.cardValue}>₹{data.gstSummary.totalTaxableSales.toLocaleString('en-IN')}</Text>
            </View>
            <View style={s.card}>
              <Text style={s.cardLabel}>GST Output (Collected)</Text>
              <Text style={s.cardValue}>₹{data.gstSummary.gstCollected.toLocaleString('en-IN')}</Text>
            </View>
          </View>

          <View style={s.grid}>
            <View style={[s.card, { borderLeftColor: '#2563eb' }]}>
              <Text style={s.cardLabel}>ITC Available</Text>
              <Text style={[s.cardValue, { color: '#2563eb' }]}>₹{data.gstSummary.itcAvailable.toLocaleString('en-IN')}</Text>
            </View>
            <View style={[s.card, { borderLeftColor: '#dc2626' }]}>
              <Text style={s.cardLabel}>Net GST Payable</Text>
              <Text style={[s.cardValue, { color: '#dc2626' }]}>₹{data.gstSummary.netGstPayable.toLocaleString('en-IN')}</Text>
            </View>
          </View>

          <View style={{ marginTop: 10, borderTopWidth: 0.5, borderTopColor: BORDER, paddingTop: 10 }}>
            <Text style={{ fontSize: 8, fontFamily: 'Helvetica-Bold', color: TEXT_MUTED, marginBottom: 4 }}>BREAKDOWN OF OUTPUT GST</Text>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: BORDER }}>
              <Text style={{ color: TEXT_DARK }}>Central GST (CGST)</Text>
              <Text style={{ fontFamily: 'Helvetica-Bold' }}>₹{data.gstSummary.cgstCollected.toLocaleString('en-IN')}</Text>
            </View>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: BORDER }}>
              <Text style={{ color: TEXT_DARK }}>State GST (SGST)</Text>
              <Text style={{ fontFamily: 'Helvetica-Bold' }}>₹{data.gstSummary.sgstCollected.toLocaleString('en-IN')}</Text>
            </View>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 }}>
              <Text style={{ color: TEXT_DARK, fontFamily: 'Helvetica-Bold' }}>Total Output GST</Text>
              <Text style={{ fontFamily: 'Helvetica-Bold', color: GREEN }}>₹{data.gstSummary.gstCollected.toLocaleString('en-IN')}</Text>
            </View>
          </View>

          <View style={s.footer}>
            <Text style={s.footerText}>{shop.name} | {periodStr}</Text>
            <Text style={s.footerText}>Page 3</Text>
            <Text style={s.footerText}>Generated by TruBill Invoice</Text>
          </View>
        </Page>
      )}

      {/* PAGE 4: TOP PRODUCTS & CUSTOMERS */}
      <Page size="A4" style={s.page}>
        <View style={s.topBar} />
        <Text style={s.sectionHeader}>Page 4 — Top Products & Customers</Text>

        <Text style={{ fontSize: 9, fontFamily: 'Helvetica-Bold', color: GREEN, marginBottom: 6, textTransform: 'uppercase' }}>Top Products by Revenue</Text>
        <View style={[s.tableHeader, { backgroundColor: GREEN }]}>
          <Text style={{ ...s.th, width: '10%' }}>Rank</Text>
          <Text style={{ ...s.th, width: '45%' }}>Product Name</Text>
          <Text style={{ ...s.th, width: '15%', textAlign: 'right' }}>Qty Sold</Text>
          <Text style={{ ...s.th, width: '20%', textAlign: 'right' }}>Revenue (₹)</Text>
          <Text style={{ ...s.th, width: '10%', textAlign: 'center' }}>Share</Text>
        </View>
        {data.topProducts.slice(0, 10).map((p: any, idx: number) => (
          <View key={p.name} style={[s.tableRow, idx % 2 === 1 ? s.tableRowAlt : {}]}>
            <Text style={{ ...s.td, width: '10%', textAlign: 'center' }}>{idx + 1}</Text>
            <Text style={{ ...s.tdBold, width: '45%' }}>{p.name}</Text>
            <Text style={{ ...s.td, width: '15%', textAlign: 'right' }}>{p.qty}</Text>
            <Text style={{ ...s.tdBold, width: '20%', textAlign: 'right' }}>{p.revenue.toFixed(2)}</Text>
            <Text style={{ ...s.td, width: '10%', textAlign: 'center' }}>{p.percentage}%</Text>
          </View>
        ))}

        <Text style={{ fontSize: 9, fontFamily: 'Helvetica-Bold', color: GREEN, marginTop: 15, marginBottom: 6, textTransform: 'uppercase' }}>Top Customers by Revenue</Text>
        <View style={[s.tableHeader, { backgroundColor: GREEN }]}>
          <Text style={{ ...s.th, width: '10%' }}>Rank</Text>
          <Text style={{ ...s.th, width: '45%' }}>Customer</Text>
          <Text style={{ ...s.th, width: '15%', textAlign: 'center' }}>Invoices</Text>
          <Text style={{ ...s.th, width: '15%', textAlign: 'right' }}>Billed (₹)</Text>
          <Text style={{ ...s.th, width: '15%', textAlign: 'right' }}>Outstanding (₹)</Text>
        </View>
        {data.topCustomers.slice(0, 5).map((c: any, idx: number) => (
          <View key={c.phone} style={[s.tableRow, idx % 2 === 1 ? s.tableRowAlt : {}]}>
            <Text style={{ ...s.td, width: '10%', textAlign: 'center' }}>{idx + 1}</Text>
            <Text style={{ ...s.tdBold, width: '45%' }}>{c.name}</Text>
            <Text style={{ ...s.td, width: '15%', textAlign: 'center' }}>{c.invoices}</Text>
            <Text style={{ ...s.tdBold, width: '15%', textAlign: 'right' }}>{c.billed.toFixed(2)}</Text>
            <Text style={{ ...s.td, width: '15%', textAlign: 'right', color: '#dc2626' }}>{c.outstanding.toFixed(2)}</Text>
          </View>
        ))}

        <View style={s.footer}>
          <Text style={s.footerText}>{shop.name} | {periodStr}</Text>
          <Text style={s.footerText}>Page 4</Text>
          <Text style={s.footerText}>Generated by TruBill Invoice</Text>
        </View>
      </Page>

      {/* PAGE 5: DAILY SALES TABLE */}
      <Page size="A4" style={s.page}>
        <View style={s.topBar} />
        <Text style={s.sectionHeader}>Page 5 — Daily Sales</Text>

        <View style={s.tableHeader}>
          <Text style={{ ...s.th, width: '25%' }}>Date</Text>
          <Text style={{ ...s.th, width: '25%', textAlign: 'center' }}>Invoices Count</Text>
          <Text style={{ ...s.th, width: '30%', textAlign: 'right' }}>Total Billed (₹)</Text>
          <Text style={{ ...s.th, width: '20%', textAlign: 'center' }}>Status</Text>
        </View>
        {data.dailySales.map((day: any, idx: number) => {
          if (day.total === 0 && !day.hasFailed) return null; // skip empty days to fit on one page
          return (
            <View key={day.day} style={[s.tableRow, idx % 2 === 1 ? s.tableRowAlt : {}]}>
              <Text style={{ ...s.td, width: '25%' }}>{day.dateLabel}</Text>
              <Text style={{ ...s.td, width: '25%', textAlign: 'center' }}>{day.count}</Text>
              <Text style={{ ...s.tdBold, width: '30%', textAlign: 'right' }}>{day.total.toFixed(2)}</Text>
              <Text style={{ ...s.td, width: '20%', textAlign: 'center', color: day.hasFailed ? '#dc2626' : '#16a34a' }}>
                {day.hasFailed ? '⚠️ Failed' : 'Active'}
              </Text>
            </View>
          );
        })}

        <View style={s.footer}>
          <Text style={s.footerText}>{shop.name} | {periodStr}</Text>
          <Text style={s.footerText}>Page 5</Text>
          <Text style={s.footerText}>Generated by TruBill Invoice</Text>
        </View>
      </Page>

      {/* PAGE 6: PURCHASES & ITC (if registered) */}
      {shop.gst_registered && data.purchasesSummary && (
        <Page size="A4" style={s.page}>
          <View style={s.topBar} />
          <Text style={s.sectionHeader}>Page 6 — Purchases & ITC</Text>

          <View style={s.grid}>
            <View style={s.card}>
              <Text style={s.cardLabel}>Total Purchases</Text>
              <Text style={s.cardValue}>₹{data.purchasesSummary.totalPurchases.toLocaleString('en-IN')}</Text>
            </View>
            <View style={s.card}>
              <Text style={s.cardLabel}>Total ITC Earned</Text>
              <Text style={s.cardValue}>₹{data.purchasesSummary.totalItcEarned.toLocaleString('en-IN')}</Text>
            </View>
          </View>

          <Text style={{ fontSize: 9, fontFamily: 'Helvetica-Bold', color: GREEN, marginBottom: 6, textTransform: 'uppercase' }}>Top Suppliers</Text>
          <View style={s.tableHeader}>
            <Text style={{ ...s.th, width: '50%' }}>Supplier Name</Text>
            <Text style={{ ...s.th, width: '25%', textAlign: 'right' }}>Purchases Amount (₹)</Text>
            <Text style={{ ...s.th, width: '25%', textAlign: 'right' }}>ITC Earned (₹)</Text>
          </View>
          {data.purchasesSummary.topSuppliers.map((sup: any, idx: number) => (
            <View key={sup.name} style={[s.tableRow, idx % 2 === 1 ? s.tableRowAlt : {}]}>
              <Text style={{ ...s.tdBold, width: '50%' }}>{sup.name}</Text>
              <Text style={{ ...s.td, width: '25%', textAlign: 'right' }}>{sup.purchases.toFixed(2)}</Text>
              <Text style={{ ...s.tdBold, width: '25%', textAlign: 'right', color: GREEN }}>{sup.itc.toFixed(2)}</Text>
            </View>
          ))}

          <View style={s.footer}>
            <Text style={s.footerText}>{shop.name} | {periodStr}</Text>
            <Text style={s.footerText}>Page 6</Text>
            <Text style={s.footerText}>Generated by TruBill Invoice</Text>
          </View>
        </Page>
      )}
    </Document>
  );
};

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const searchParams = request.nextUrl.searchParams;
  const month = parseInt(searchParams.get('month') || String(new Date().getMonth() + 1), 10);
  const year = parseInt(searchParams.get('year') || String(new Date().getFullYear()), 10);

  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { data: shop } = await supabase.from('shops').select('*').eq('auth_user_id', user.id).single();
    if (!shop) return NextResponse.json({ error: 'Shop not found' }, { status: 404 });

    // Call local server endpoint to fetch the reports JSON data directly
    const reqUrl = new URL(request.url);
    const origin = reqUrl.origin;
    const res = await fetch(`${origin}/api/reports/data?month=${month}&year=${year}`, {
      headers: {
        cookie: request.headers.get('cookie') || '',
      },
    });

    if (!res.ok) throw new Error('Failed to fetch report data');
    const data = await res.json();

    const buffer = await renderToBuffer(
      <ReportPDFDocument shop={shop} month={month} year={year} data={data} />
    );

    const monthName = MONTHS[month - 1];
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="TruBill_Report_${shop.name.replace(/\s+/g, '_')}_${monthName}${year}.pdf"`,
      },
    });
  } catch (err: any) {
    console.error('Report PDF generation API error:', err);
    return NextResponse.json({ error: err.message || 'Failed to generate PDF' }, { status: 500 });
  }
}
